import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.9
blur = true
  [window.padding]
    x = 0
    y = 0
  [window.position]
  x = 0
  y = 0


[font]
normal.family = "MesloLGS NF"
size = 14

[selection]
save_to_clipboard = true
